#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.shihy.springboot.entity
  mapperLocations: classpath:mapping/*.xml

---

#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude: WEB-INF/**

#开发配置
spring:
  profiles: dev
  application:
    name: springstart
  #◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁mysql配置▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=GBK
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    #type: com.alibaba.druid.pool.DruidDataSource
  ###rabbitmq
  rabbitmq.host: 127.0.0.1
  rabbitmq.port: 5672
  rabbitmq.username: guest
  rabbitmq.password: guest
  ###上传文件
  # 禁用 thymeleaf 缓存
  thymeleaf.cache: false
  
  #◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁redis配置▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷
  redis:
    ##cluster:
      ##max-redirects: 1
    pool:
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-active: 8
      # 连接池中的最大空闲连接 默认 8
      max-idle: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-wait: -1
      # 连接池中的最小空闲连接 默认 0
      min-idle: 0
    host: localhost
    port: 6379
    ##一主三从的的配置方式来提高缓存的吞吐量
    ##sentinel:
      ##nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
      ##master: localhost
    ### Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    timeout: 10000
    
  #◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁◁文件上传配置▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷▷
  http:
    multipart:
      # # 上传文件的临时目录 （一般情况下不用特意修改）
      location: 
      ## 是否支持批量上传   (默认值 true)
      enabled: true
       ##文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中，（默认值0 一般情况下不用特意修改）
      file-size-threshold: 0
      ##上传文件最大为 10M （默认值 1M）
      max-file-size: 10485760
      ## 判断是否要延迟解析文件（相当于懒加载，一般情况下不用特意修改）
      resolve-lazily: false
      
  ##屏蔽登录
security:
  basic:
    enabled: false

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/         
         
      register-with-eureka: false
      fetch-registry: false
      healthcheck:
        enabled: true
   instance:
      hostname: localhost     
      ip-address: true
      
# 打印sql
logging:
  level:
    com.shihy.springboot.dao : debug