package com.bestinfo.sql;

//package com.bestinfo.dao.sqlmap;
//
///**
// * 游戏抽奖规则
// *
// * @author chenliping
// */
//public class GameRaffleRuleSql {
//    
//    public static String INSERT_GAME_RAFFLE_RULE = "INSERT INTO T_GAME_RAFFLE_RULE VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)";
//
//    public static String SELECT_GAME_RAFFLE_RULE_BYGAMEID = "SELECT GAME_ID,PLAY_ID,OPEN_ID,CLASS_ID,RULE_ID,BASIC_NUM,SPECIAL_NUM,BLUE_NUM,NO_ORDER,MATCH_POS,MATCH_NEAR,RAFFLE_METHOD,WORK_STATUS from T_GAME_RAFFLE_RULE where GAME_ID=?";
//    
//    public static String SELECT_GAME_RAFFLE_RULE_BYRULEID = "SELECT GAME_ID,PLAY_ID,OPEN_ID,CLASS_ID,RULE_ID,BASIC_NUM,SPECIAL_NUM,BLUE_NUM,NO_ORDER,MATCH_POS,MATCH_NEAR,RAFFLE_METHOD,WORK_STATUS from T_GAME_RAFFLE_RULE where RULE_ID=?";
//    
//    public static String SELECT_GAME_RAFFLE_RULE_BYIDS = "SELECT GAME_ID,PLAY_ID,OPEN_ID,CLASS_ID,RULE_ID,BASIC_NUM,SPECIAL_NUM,BLUE_NUM,NO_ORDER,MATCH_POS,MATCH_NEAR,RAFFLE_METHOD,WORK_STATUS from T_GAME_RAFFLE_RULE where GAME_ID=? and PLAY_ID=? and RULE_ID=?";
//    
//    public static String SELECT_GAME_RAFFLE_RULE_LIST = "SELECT GAME_ID,PLAY_ID,OPEN_ID,CLASS_ID,RULE_ID,BASIC_NUM,SPECIAL_NUM,BLUE_NUM,NO_ORDER,MATCH_POS,MATCH_NEAR,RAFFLE_METHOD,WORK_STATUS from T_GAME_RAFFLE_RULE";
//   
//    public static String UPDATE_GAME_RAFFLE_RULE = "UPDATE T_GAME_RAFFLE_RULE SET OPEN_ID=?,PLAY_ID=?,CLASS_ID=?,BASIC_NUM=?,SPECIAL_NUM=?,BLUE_NUM=?,NO_ORDER=?,MATCH_POS=?,MATCH_NEAR=?,RAFFLE_METHOD=?,WORK_STATUS=? WHERE GAME_ID=? and RULE_ID=?";
//}
