package com.bestinfo.gambler.swing;

import com.bestinfo.arithmetic.NewSign;
import com.bestinfo.gambler.all.StaticVariable;
import com.bestinfo.gambler.all.HttpSend;
import com.bestinfo.gambler.batch.BatchRechargeTask;
import com.bestinfo.gambler.batch.BetTicketPac;
import com.bestinfo.gambler.batch.TaskManager;
import com.bestinfo.gambler.batch.TmnSelectDao;
import com.bestinfo.gambler.createBetNumber.Count;
import com.bestinfo.protocols.client.agents.PAgentRechargeUserClient;
import com.bestinfo.gambler.protocols.ActionID;
import com.bestinfo.protocols.agents.AgentRechargeUserInfo;
import com.bestinfo.protocols.agents.AgentRechargeUserReqList;
import com.bestinfo.protocols.agents.AgentRechargeUserReqResList;
import com.bestinfo.protocols.message.APPMessage;
import com.bestinfo.protocols.message.AppHeader;
import com.bestinfo.redis.login.DealerLoginRedis;
import java.io.UnsupportedEncodingException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import javax.annotation.Resource;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author jone
 */
public class DealerRechargeAgent extends javax.swing.JFrame {

    private static Logger logger = Logger.getLogger(DealerRechargeAgent.class);

    @Resource
    private DealerLoginRedis dealerlogin;

    /**
     * Creates new form DealerRechargeAgent
     */
    public DealerRechargeAgent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        no1 = new javax.swing.JTextField();
        gamblername1 = new javax.swing.JTextField();
        gamblerpwd1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        charge1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sendtype = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dealer_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        terminal_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Mobile = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        charge2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        charge3 = new javax.swing.JTextField();
        charge4 = new javax.swing.JTextField();
        charge5 = new javax.swing.JTextField();
        charge6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        from = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        eachnum5 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        eachnum2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel3.setText("运营商管理员:");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel5.setText("运营商管理员密码:");

        jLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel6.setText("代理充值彩民个数:");

        jButton2.setText("提交");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        no1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        no1.setText("1");
        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });

        gamblername1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        gamblername1.setText("qqqq");
        gamblername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamblername1ActionPerformed(evt);
            }
        });

        gamblerpwd1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        gamblerpwd1.setText("111111");
        gamblerpwd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamblerpwd1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel7.setText("                             运营商代理充值");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("充值类型：支付宝1，银行卡2，手机话费3，现金4，\n虚拟帐户5\n可以不填");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel10.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel10.setText("充值类型:");

        charge1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        charge1.setText("5");
        charge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charge1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel1.setText("发送方类型：");

        sendtype.setText("4");
        sendtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtypeActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel13.setText("电话号码：");

        Phone.setText("020-00000000");
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel2.setText("运营商ID：");

        dealer_id.setText("146");
        dealer_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealer_idActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel4.setText("终端机号：");

        terminal_id.setText("14610001");
        terminal_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminal_idActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel8.setText("手机号：");

        Mobile.setText("15811111111");
        Mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel11.setText("充值金额:");

        charge2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        charge2.setText("0@12@34@55");
        charge2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charge2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel16.setText("流水号自定标识:");

        charge3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        charge3.setText("8888");
        charge3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charge3ActionPerformed(evt);
            }
        });

        charge4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        charge4.setText("全民付");
        charge4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charge4ActionPerformed(evt);
            }
        });

        charge5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        charge5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charge5ActionPerformed(evt);
            }
        });

        charge6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        charge6.setText("101110200006300044");
        charge6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charge6ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel12.setText("运营商负责人:");

        jLabel14.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel14.setText("彩民姓名:");

        jLabel15.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel15.setText("身份证件编号:");

        jButton3.setText("批量提交");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        from.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        from.setText("14610001");
        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel17.setText("from:");

        jLabel18.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel18.setText("to:");

        to.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        to.setText("14610100");
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });

        jLabel57.setText("成功数目：");

        eachnum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eachnum5ActionPerformed(evt);
            }
        });

        jLabel55.setText("用时");

        eachnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eachnum2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel57))
                                    .addComponent(eachnum5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel55)
                                    .addComponent(eachnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(charge2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(charge4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(charge5)
                                            .addComponent(charge6)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(gamblerpwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(no1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(gamblername1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(charge1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(charge3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(terminal_id)
                                    .addComponent(dealer_id)
                                    .addComponent(Phone)
                                    .addComponent(sendtype))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gamblername1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sendtype, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gamblerpwd1)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealer_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charge1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(terminal_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(charge3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charge2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charge5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(charge4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(charge6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eachnum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eachnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileActionPerformed

    private void terminal_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminal_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terminal_idActionPerformed

    private void dealer_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealer_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dealer_idActionPerformed

    private void sendtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendtypeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            int actionID = ActionID.DEALER_AGENTRECHARGE;

            AppHeader head = new AppHeader();
            head.setType(Integer.parseInt(sendtype.getText()));//发送方类型    自助终端运营商4
            head.setAction(actionID);//协议编号
            head.setVersion(0);//version版本号(填0)
            head.setDealer_id(dealer_id.getText());//head.setDealer_id("111");//运营商ID
            head.setTerminal_id(Integer.parseInt(terminal_id.getText()));//head.setTerminal_id("111");//终端机号
            head.setMobile(Mobile.getText());//手机号(填0)head.setMobile("15101105612");
            head.setPhone(Phone.getText());//电话号码(填0)   head.setPhone("15101105612");
            head.setSent_time(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));//发送时间head.setSent_time("2015-07-29 12:12:12");
            //  head.setSign(new byte[0]);//head.setSign("1231321".getBytes());//报文体签名

            AgentRechargeUserReqList req = new AgentRechargeUserReqList();
            AgentRechargeUserInfo ar = new AgentRechargeUserInfo();
            List<AgentRechargeUserInfo> agentUserList = new ArrayList<AgentRechargeUserInfo>();

            req.setDealerManager(gamblername1.getText());
            req.setPwd(gamblerpwd1.getText());
            //new String(charge4.getText().getBytes("utf-8"),"utf-8");
            try {
                req.setOwnerName(new String(charge4.getText().getBytes("GBK"), "GBK"));
            } catch (UnsupportedEncodingException ex) {
                logger.error(ex);
            }
            req.setIdNo(charge6.getText());
            System.out.println(req + "--requ--------");
            ar.setGamblerName(charge5.getText());
            ar.setDealerSerial(charge2.getText());
            ar.setRechargeMoney(new BigDecimal(charge3.getText()));
            ar.setRechargeType(Integer.valueOf(charge1.getText()));
            ar.setRechargeTime(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(head.getSent_time()));
            agentUserList.add(ar);
            req.setAgentUserList(agentUserList);
            //把报文转换成XML

            PAgentRechargeUserClient recharge = new PAgentRechargeUserClient();
            String requestxml = recharge.generateXML(head, req);
            // String requestxml = XmlFactoryClient.getInstance().getAppClientXF(actionID).generateXML(head, req);

//            String sessionKey = (String) CacheManager.getCacheInfo("sessionKey").getValue();
//            logger.info("sessionKey is: " + sessionKey);
//            if (sessionKey == null) {
//                logger.info("sessionKey is null");
//            }
//            byte[] ret_key = NewSign.GetSign(requestxml, "d:/gdclient.p12", "gdtest@2015", "cosmos", sessionKey);
            byte[] ret_key = NewSign.GetSign(requestxml, StaticVariable.privateKey, StaticVariable.SESSION);

            head.setBody_sign(ret_key);
            requestxml = recharge.generateXML(head, req);

            //拼接发送XML
            String xml = "action=" + actionID + "&" + requestxml;
            System.out.println("xml is ===============   " + xml);
            //发送xml并取回回复XML
            String responsexml = HttpSend.httpSend(StaticVariable.SERVERURL, xml);
            // String responsexml = HttpUtil.httpSend(xml, StaticVariable.SERVERURL, true);//StaticVariable.SERVERURL服务器地址
            System.out.println("responsexml is ===============   " + responsexml);

            //解析XML
            APPMessage ap = recharge.parseXML(responsexml);

            //APPMessage ap =XmlFactoryClient.getInstance().getAppClientXF(actionID).parseXML(responsexml);
            //回复报文
            AgentRechargeUserReqResList tbrr = (AgentRechargeUserReqResList) ap.getContent();//得到返回内容
            int resultcode = tbrr.getAppResResult().getResultCode();
            //输出结果
            if (resultcode == 0) {
                System.out.println("send successfull");
            } else {
                System.out.println(resultcode + "\t" + tbrr.getAppResResult().getResultDes());
            }
            JOptionPane.showMessageDialog(this, "返回码:" + resultcode + "结果:" + tbrr.getAppResResult().getResultDes(), "操作", JOptionPane.INFORMATION_MESSAGE);

//        String threadnum = size1.getText();
//        String eachno = size3.getText();
//        if (threadnum.isEmpty() || eachno.isEmpty()) {
//            return;
//        }
//        AgentAbstractUserReqList aruu = new AgentAbstractUserReqList();
//        String name = gamblername1.getText();
//        String pwd = gamblerpwd1.getText();
//        String noa = no1.getText();
//        String ser1 = sert.getText();
//        aruu.setDealerManager(name);
//        aruu.setPwd(pwd);
//        String chargeid = charge1.getText();
//        try {
//            new GamblerAccountinfo().moreDealer_get_moneythread(ser1, header, aruu, Integer.parseInt(noa), chargeid, Integer.parseInt(threadnum), Integer.parseInt(eachno));
//        } catch (Exception e) {
//            logger.error(e);
//        }
        } catch (Exception ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void gamblerpwd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamblerpwd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gamblerpwd1ActionPerformed

    private void gamblername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamblername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gamblername1ActionPerformed

    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no1ActionPerformed

    private void charge4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charge4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charge4ActionPerformed

    private void charge6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charge6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charge6ActionPerformed

    private void charge5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charge5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charge5ActionPerformed

    private void charge2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charge2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charge2ActionPerformed

    private void charge3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charge3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charge3ActionPerformed

    private void charge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charge1ActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Count count = new Count();
            int dealerid = Integer.parseInt(dealer_id.getText().trim());
            if (dealerid == 145 || dealerid == 146) {
                Set<Integer> set = new HashSet<>();
                int fromInt = Integer.parseInt(from.getText().trim());
                int toInt = Integer.parseInt(to.getText().trim());
                try {
                    //查询t_tmn_info表中的终端机号
                    TmnSelectDao.getTerminalId(dealerid, fromInt, toInt, set);
                } catch (Exception ex) {
                    java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
                logger.info("查询t_tmn_info表中的终端机号结果为 ：" + set.toString());
                long startTime = System.currentTimeMillis();
                for (Integer terminalid : set) {
                    AppHeader head = new AppHeader();
                    head.setType(Integer.parseInt(sendtype.getText()));//发送方类型    自助终端运营商4
                    head.setAction(ActionID.DEALER_AGENTRECHARGE);//协议编号
                    head.setVersion(0);//version版本号(填0)
                    head.setDealer_id(dealer_id.getText());//head.setDealer_id("111");//运营商ID
                    head.setTerminal_id(terminalid);//head.setTerminal_id("111");//终端机号
                    head.setMobile(Mobile.getText());//手机号(填0)head.setMobile("15101105612");
                    head.setPhone(Phone.getText());//电话号码(填0)   head.setPhone("15101105612");
                    head.setSent_time(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));//发送时间head.setSent_time("2015-07-29 12:12:12");

                    AgentRechargeUserReqList req = new AgentRechargeUserReqList();
                    AgentRechargeUserInfo ar = new AgentRechargeUserInfo();
                    List<AgentRechargeUserInfo> agentUserList = new ArrayList<AgentRechargeUserInfo>();

                    req.setDealerManager(gamblername1.getText());
                    req.setPwd(gamblerpwd1.getText());
                    try {
                        req.setOwnerName(new String(charge4.getText().getBytes("UTF-8"), "UTF-8"));

                    } catch (UnsupportedEncodingException ex) {
                        logger.error(ex);
                    }

                    req.setIdNo(charge6.getText());
                    System.out.println(req + "--requ--------");
                    ar.setGamblerName(charge5.getText());
                    String time = new Date().getTime() + "";
                    ar.setDealerSerial("0@12@1@" + time.substring(10) + head.getTerminal_id());
                    ar.setRechargeMoney(new BigDecimal(charge3.getText()));
                    ar.setRechargeType(Integer.valueOf(charge1.getText()));
                    ar.setRechargeTime(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(head.getSent_time()));
                    agentUserList.add(ar);
                    req.setAgentUserList(agentUserList);

                    TaskManager.getInstance().execute(new BatchRechargeTask(head, req));
                }
                long endtTime = System.currentTimeMillis();
                logger.info("共用时间是多少呢？？？:" + (endtTime - startTime) / 1000F + "秒");
            } else {//140\141无自助终端
                List list = null;
                long stsrtTime = System.currentTimeMillis();
                AgentRechargeUserReqList req = new AgentRechargeUserReqList();
                AgentRechargeUserInfo ar = new AgentRechargeUserInfo();
                List<AgentRechargeUserInfo> agentUserList = new ArrayList<AgentRechargeUserInfo>();
                AppHeader head = new AppHeader();
                head.setType(Integer.parseInt(sendtype.getText()));//发送方类型    自助终端运营商4
                head.setAction(ActionID.DEALER_AGENTRECHARGE);//协议编号
                head.setVersion(0);//version版本号(填0)
                head.setDealer_id(dealer_id.getText());//head.setDealer_id("111");//运营商ID
                head.setTerminal_id(Integer.parseInt(terminal_id.getText()));//head.setTerminal_id("111");//终端机号
                head.setMobile(Mobile.getText());//手机号(填0)head.setMobile("15101105612");
                head.setPhone(Phone.getText());//电话号码(填0)   head.setPhone("15101105612");
                head.setSent_time(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));//发送时间head.setSent_time("2015-07-29 12:12:12");

                req.setDealerManager(gamblername1.getText());
                req.setPwd(gamblerpwd1.getText());
                try {
                    req.setOwnerName(new String(charge4.getText().getBytes("UTF-8"), "UTF-8"));
                } catch (UnsupportedEncodingException ex) {
                    logger.error(ex);
                }
                //  req.setOwnerName(charge4.getText());
                System.out.println(" req.setOwnerNam: " + req.getOwnerName());
                req.setIdNo(charge6.getText());
                ar.setRechargeMoney(new BigDecimal(charge3.getText()));
                ar.setRechargeType(Integer.valueOf(charge1.getText()));
                ar.setRechargeTime(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(head.getSent_time()));
                agentUserList.add(ar);
                req.setAgentUserList(agentUserList);

                BetTicketPac bt = new BetTicketPac();
                bt.execRechargeBatch(Integer.valueOf(from.getText()), Integer.valueOf(to.getText()), req, ar, count, head);
                long endtTime = System.currentTimeMillis();
                eachnum2.setText(StaticVariable.TASTE_TIME + "");
                //  logger.info("共用时间为" + (endtTime - stsrtTime) / 1000F);
                eachnum5.setText(count.getCount() + "");
//                eachnum2.setText(StaticVariable.TASTE_TIME + "");
//                logger.info("共用时间为" + (endtTime - stsrtTime) / 1000F);
//                eachnum5.setText(count.getCount() + "");
//                eachnum4.setText(count.getFailcount() + "");

//                try {
//                    //查询用户名列表
//                    list = GamblerInfoDao.getGambInfo(dealer_id.getText());
//                } catch (Exception ex) {
//                    java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                logger.info("查询t_tmn_info表中的终端机号结果为 ：" + list.toString());
//                long startTime = System.currentTimeMillis();
//                for (Object gamblerInfo : list) {
//                    AppHeader head = new AppHeader();
//                    head.setType(Integer.parseInt(sendtype.getText()));//发送方类型    自助终端运营商4
//                    head.setAction(ActionID.DEALER_AGENTRECHARGE);//协议编号
//                    head.setVersion(0);//version版本号(填0)
//                    head.setDealer_id(dealer_id.getText());//head.setDealer_id("111");//运营商ID
//                    head.setTerminal_id(0);//head.setTerminal_id("111");//终端机号
//                    head.setMobile(Mobile.getText());//手机号(填0)head.setMobile("15101105612");
//                    head.setPhone(Phone.getText());//电话号码(填0)   head.setPhone("15101105612");
//                    head.setSent_time(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));//发送时间head.setSent_time("2015-07-29 12:12:12");
//
//                    AgentRechargeUserReqList req = new AgentRechargeUserReqList();
//                    AgentRechargeUserInfo ar = new AgentRechargeUserInfo();
//                    List<AgentRechargeUserInfo> agentUserList = new ArrayList<AgentRechargeUserInfo>();
//
//                    req.setDealerManager(gamblername1.getText());
//                    req.setPwd(gamblerpwd1.getText());
//                    try {
//                        req.setOwnerName(new String(charge4.getText().getBytes("utf8"), "utf8"));
//                    } catch (UnsupportedEncodingException ex) {
//                        logger.error(ex);
//                    }
//                    req.setIdNo(charge6.getText());
//
//                    //多线程 执行多个用户
//                    ar.setGamblerName(((GamblerInfo) gamblerInfo).getGambler_name());
//                    String time = new Date().getTime() + "";
//                    ar.setDealerSerial("0@12@1@" + time.substring(3) + ar.getGamblerName());
//                    Cache d = new Cache();
////            logger.info("返回sessionKey: "+dc.bytes2HexString(pwd_dec));
////            d.setValue(dc.bytes2HexString(pwd_dec));
//                    d.setValue(ar.getDealerSerial());
////            int dealerid = Integer.parseInt(dealer_id.getText().trim());
////            if(dealerid == 145 ||dealerid == 146){ 
////                String terminal_id = String.valueOf(head.getTerminal_id());//请求的终端机号
////                CacheManager.putCache(terminal_id, d);//将响应信息 以一个终端机号对应一个sessionkey的形式缓存
////                System.out.println(CacheManager.getCacheInfo(terminal_id).getValue()) ;
////            }else{
//                    CacheManager.putCache(ar.getGamblerName(), d);
//                    ar.setRechargeMoney(new BigDecimal(charge3.getText()));
//                    ar.setRechargeType(Integer.valueOf(charge1.getText()));
//                    ar.setRechargeTime(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(head.getSent_time()));
//                    agentUserList.add(ar);
//                    req.setAgentUserList(agentUserList);
//
//                    TaskManager.getInstance().execute(new BatchRechargeTask(head, req));
//                }
//                long endtTime = System.currentTimeMillis();
//                logger.info("共用时间是多少呢？？？:" + (endtTime - startTime) / 1000F + "秒");
            }
        } catch (Exception ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void eachnum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eachnum5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eachnum5ActionPerformed

    private void eachnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eachnum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eachnum2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DealerRechargeAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DealerRechargeAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DealerRechargeAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DealerRechargeAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DealerRechargeAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Mobile;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField charge1;
    private javax.swing.JTextField charge2;
    private javax.swing.JTextField charge3;
    private javax.swing.JTextField charge4;
    private javax.swing.JTextField charge5;
    private javax.swing.JTextField charge6;
    private javax.swing.JTextField dealer_id;
    private javax.swing.JTextField eachnum2;
    private javax.swing.JTextField eachnum5;
    private javax.swing.JTextField from;
    private javax.swing.JTextField gamblername1;
    private javax.swing.JTextField gamblerpwd1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField no1;
    private javax.swing.JTextField sendtype;
    private javax.swing.JTextField terminal_id;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
