/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bestinfo.gambler.swing;

import com.bestinfo.arithmetic.NewSign;
import com.bestinfo.bean.sysUser.DealerLogin;
import com.bestinfo.gambler.all.StaticVariable;
import com.bestinfo.gambler.all.HttpSend;
import com.bestinfo.gambler.cache.CacheManager;
import com.bestinfo.protocols.client.bet.PGameRuleInfoDownClient;
import com.bestinfo.gambler.protocols.ActionID;
import com.bestinfo.protocols.bet.GameRuleInfoReq;
import com.bestinfo.protocols.bet.GameRuleInfoReqResList;
import com.bestinfo.protocols.message.APPMessage;
import com.bestinfo.protocols.message.AppHeader;
import com.bestinfo.protocols.users.GamblerRegistReqRes;
import com.bestinfo.redis.login.DealerLoginRedis;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.annotation.Resource;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author Admin
 */
public class GameRuleInfoDown extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(GameRuleInfoDown.class);

    @Resource
    private DealerLoginRedis dealerlogin;

    /**
     * Creates new form GameRuleInfoDown1
     */
    public GameRuleInfoDown() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        game_id = new javax.swing.JTextField();
        bt_down = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sendtype3 = new javax.swing.JTextField();
        sendtype4 = new javax.swing.JTextField();
        sendtype5 = new javax.swing.JTextField();
        sendtype7 = new javax.swing.JTextField();
        sendtype6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel2.setText("游戏编号：");

        game_id.setToolTipText("");
        game_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game_idActionPerformed(evt);
            }
        });

        bt_down.setText("下载");
        bt_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_downActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel1.setText("游戏规则文件下载");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel4.setText("手机号");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel5.setText("电话");

        jLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel6.setText("终端机号");

        jLabel7.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel7.setText("运营商编号");

        jLabel8.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel8.setText("发送方类型");

        sendtype3.setText("3");
        sendtype3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtype3ActionPerformed(evt);
            }
        });

        sendtype4.setText("153");
        sendtype4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtype4ActionPerformed(evt);
            }
        });

        sendtype5.setText("100");
        sendtype5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtype5ActionPerformed(evt);
            }
        });

        sendtype7.setText("0");
        sendtype7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtype7ActionPerformed(evt);
            }
        });

        sendtype6.setText("0");
        sendtype6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtype6ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sendtype6)
                            .addComponent(sendtype3)
                            .addComponent(sendtype5, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sendtype4, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(sendtype7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(game_id)))
                        .addGap(0, 220, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(bt_down, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sendtype3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendtype4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sendtype5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(sendtype7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(sendtype6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(game_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(bt_down)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_downActionPerformed
        // TODO add your handling code here:
        try {
//            AppHeader headtemp = StaticVariable.head;
//
//            int actionID = ActionID.GAMERULE_DOWNLOAD;
//
//            headtemp.setAction(actionID);
//
//            if (headtemp == null) {
//                logger.error("没有初始化信息！");
//                return;
//            }
            
             DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            int actionID = ActionID.GAMERULE_DOWNLOAD;
            AppHeader head = new AppHeader();

            head.setType(Integer.parseInt(sendtype3.getText()));//head.setType(1);//发送方类型
            head.setAction(actionID);//协议编号
            head.setVersion(0);//version版本号(填0)
            head.setDealer_id(sendtype4.getText());//head.setDealer_id("111");//运营商ID
            head.setTerminal_id(Integer.parseInt(sendtype5.getText()));//head.setTerminal_id("111");//终端机号
            head.setMobile(sendtype7.getText());//手机号(填0)head.setMobile("15101105612");
            head.setPhone(sendtype6.getText());//电话号码(填0)   head.setPhone("15101105612");
            head.setSent_time(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
            

            String strGame_ID = game_id.getText();
            logger.info("strAGame_ID "+strGame_ID);
            if (strGame_ID.isEmpty()) {
                logger.error("游戏编号不能为空！");
                return;
            }

            GameRuleInfoReq req = new GameRuleInfoReq();
            List<Integer> lGame_IDs = new ArrayList();
            String[] strAGame_ID = strGame_ID.split(",");
            logger.info("strAGame_ID len"+strAGame_ID.length);
            for (int i = 0; i < strAGame_ID.length; i++) {
                lGame_IDs.add(Integer.parseInt(strAGame_ID[i]));
            }

            req.setGameIds(lGame_IDs);

            PGameRuleInfoDownClient ps = new PGameRuleInfoDownClient();
            String s = ps.generateXML(head, req);
//            UserLoginReqRes ur = new UserLoginReqRes();
//            String str_key = ur.getSession_key();
            String str_key = null;
            /*DealerLogin dl = dealerlogin.getDealerLoginInfo(Integer.parseInt(headtemp.getDealer_id()), headtemp.getTerminal_id());
            if (dl != null && dl.getSessionkey() != null && !dl.getSessionkey().isEmpty()) {
                str_key = dl.getSessionkey();
                logger.error("Sessionkey:" + str_key);
            }

            System.out.println("key:" + str_key);
            // byte[] ret_key = NewSign.GetS(s, "e:/gdtestp12.cer", str_key);
            byte[] ret_key = NewSign.GetSign(s, "d:/gdclient.p12", "gdtest@2015", "gdtest@2015", "Pc1+WguxbZmA1Q4H2aTHRw==");
            System.out.println("ret_key len:" + ret_key.length);*/
            
//             String sessionKey = (String) CacheManager.getCacheInfo("sessionKey").getValue();
//            logger.info("sessionKey is: " + sessionKey);
//            if (sessionKey == null) {
//                logger.info("sessionKey is null");
//            }
//            byte[] ret_key = NewSign.GetSign(s, "d:/gdclient.p12", "gdtest@2015", "cosmos", sessionKey);
            // byte[] ret_key = NewSign.GetS(requestxml, "d:/gdtestp12.cer", str_key);
            //byte[] ret_key = NewSign.GetSign(s, FilePath.getStorePath(), FilePath.getAliaspwd(), FilePath.getAlias(), str_key);
        
            byte[] ret_key = NewSign.GetSign(s, StaticVariable.privateKey, StaticVariable.SESSION);

            //byte[] ret_key = NewSign.GetSign(s, FilePath.getStorePath(), FilePath.getAliaspwd(), FilePath.getAlias(), str_key);
            head.setBody_sign(ret_key);
            System.out.println(s);

            s = ps.generateXML(head, req);

            //拼接发送XML
            String xml = "action=" + actionID + "&" + s;
            System.out.println(xml);

            String responsexml = HttpSend.httpSend(StaticVariable.SERVERURL, xml);
            jTextArea1.setText(responsexml);
            APPMessage ap = ps.parseXML(responsexml);

            //   APPMessage ap = XmlFactoryClient.getInstance().getAppClientXF(actionID).parseXML(responsexml);
//        //回复报文
            GameRuleInfoReqResList tbrr = (GameRuleInfoReqResList) ap.getContent();//得到返回内容
            int resultcode = tbrr.getAppResResult().getResultCode();
//        //输出结果
            if (resultcode == 0) {
                System.out.println("send successfull");
            } else {
                System.out.println(resultcode + "\t" + tbrr.getAppResResult().getResultDes());
            }
            JOptionPane.showMessageDialog(this, "返回码:" + resultcode + "结果:" + tbrr.getAppResResult().getResultDes(), "操作", JOptionPane.INFORMATION_MESSAGE);

            System.out.println(responsexml);
        } catch (Exception exx) {
        }

    }//GEN-LAST:event_bt_downActionPerformed

    private void game_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_game_idActionPerformed

    private void sendtype3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtype3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendtype3ActionPerformed

    private void sendtype4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtype4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendtype4ActionPerformed

    private void sendtype5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtype5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendtype5ActionPerformed

    private void sendtype7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtype7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendtype7ActionPerformed

    private void sendtype6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtype6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendtype6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameRuleInfoDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameRuleInfoDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameRuleInfoDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameRuleInfoDown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameRuleInfoDown().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_down;
    private javax.swing.JTextField game_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField sendtype3;
    private javax.swing.JTextField sendtype4;
    private javax.swing.JTextField sendtype5;
    private javax.swing.JTextField sendtype6;
    private javax.swing.JTextField sendtype7;
    // End of variables declaration//GEN-END:variables

}
