/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bestinfo.gambler.swing;

import com.bestinfo.gambler.all.StaticVariable;
import com.bestinfo.gambler.all.RhClientProperties;
import com.bestinfo.gambler.protocols.ActionID;
import com.bestinfo.protocols.message.AppHeader;
import java.io.File;
import java.io.FileInputStream;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.util.Date;
import org.apache.log4j.Logger;

/**
 *
 * @author J
 */
public class MyMain extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(MyMain.class);
    private static final String KEY_STORE = "PKCS12";//keystore格式

    /**
     * Creates new form Main
     */
    public MyMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        serverUrl = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sendtype = new javax.swing.JTextField();
        dealer_id = new javax.swing.JTextField();
        terminal_id = new javax.swing.JTextField();
        Mobile = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        login = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem15 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem7 = new javax.swing.JRadioButtonMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem8 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem12 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JRadioButtonMenuItem();
        jRB_DrawInfo = new javax.swing.JRadioButtonMenuItem();
        jRB_OpenPrize = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem13 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem14 = new javax.swing.JRadioButtonMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jRadioButtonMenuItem9 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem10 = new javax.swing.JRadioButtonMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jRadioButtonMenuItem11 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu5.setText("jMenu5");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel1.setText("服务地址");

        serverUrl.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        serverUrl.setText("http://192.168.26.224:8615/gambler/gambler");
        serverUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverUrlActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButton1.setText("保存");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveserverUrl(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel2.setText("第一步：先填入server address 保存；第二步：点击菜单进行操作");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel3.setText("发送方类型");

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel4.setText("运营商ID");

        jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel5.setText("终端机号");

        jLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel6.setText("手机号");

        jLabel7.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel7.setText("电话号码");

        sendtype.setText("3");
        sendtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtypeActionPerformed(evt);
            }
        });

        dealer_id.setText("160");

        terminal_id.setText("100");

        Mobile.setText("15101105612");

        Phone.setText("15101105612");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Phone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(Mobile, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(terminal_id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dealer_id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendtype)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(serverUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sendtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dealer_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(terminal_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("用户");
        jMenu1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRegister(evt);
            }
        });

        jRadioButtonMenuItem5.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("注册");
        jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem5);

        login.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        login.setSelected(true);
        login.setText("登录/登出/注销");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login(evt);
            }
        });
        jMenu1.add(login);

        jRadioButtonMenuItem15.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem15.setSelected(true);
        jRadioButtonMenuItem15.setText("多线程投注");
        jRadioButtonMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem15Register(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem15);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("查询");
        jMenu3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        jRadioButtonMenuItem2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("查询彩民信息/修改密码");
        jRadioButtonMenuItem2.setActionCommand("");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem4.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("查询彩民账号信息");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryaccount(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("银行卡操作");
        jMenu4.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        jRadioButtonMenuItem7.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem7.setSelected(true);
        jRadioButtonMenuItem7.setText("绑定解绑");
        jRadioButtonMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bindcard(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("修改");
        jMenu6.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        jRadioButtonMenuItem6.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem6.setSelected(true);
        jRadioButtonMenuItem6.setText("修改信息");
        jRadioButtonMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modify(evt);
            }
        });
        jMenu6.add(jRadioButtonMenuItem6);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("投注");
        jMenu2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbetmore(evt);
            }
        });

        jMenuItem2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jMenuItem2.setText("对时");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sysTime(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jRadioButtonMenuItem8.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem8.setSelected(true);
        jRadioButtonMenuItem8.setText("多线程投注");
        jRadioButtonMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbetnumber(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem8);

        jRadioButtonMenuItem3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("生成号码文件");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatBetNumber(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem12.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem12.setSelected(true);
        jRadioButtonMenuItem12.setText("投注查询");
        jRadioButtonMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem12creatBetNumber(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem12);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("注销");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("下载");
        jMenu7.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        jMenu8.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jMenu8.setSelected(true);
        jMenu8.setText("游戏规则文件下载");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenu8);

        jRB_DrawInfo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRB_DrawInfo.setSelected(true);
        jRB_DrawInfo.setText("奖期信息下载");
        jRB_DrawInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_DrawInfoActionPerformed(evt);
            }
        });
        jMenu7.add(jRB_DrawInfo);

        jRB_OpenPrize.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRB_OpenPrize.setSelected(true);
        jRB_OpenPrize.setText("开奖公告查询");
        jRB_OpenPrize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_OpenPrizeActionPerformed(evt);
            }
        });
        jMenu7.add(jRB_OpenPrize);

        jRadioButtonMenuItem13.setSelected(true);
        jRadioButtonMenuItem13.setText("文件下载地址查询");
        jRadioButtonMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem13ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem13);

        jRadioButtonMenuItem14.setSelected(true);
        jRadioButtonMenuItem14.setText("文件下载");
        jRadioButtonMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem14ActionPerformed(evt);
            }
        });
        jMenu7.add(jRadioButtonMenuItem14);

        jMenuBar1.add(jMenu7);

        jMenu9.setText("运营商代理");
        jMenu9.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jMenuItem3.setText("充值");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jMenuItem4.setText("提款");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem4);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("代理查询");
        jMenu10.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        jRadioButtonMenuItem9.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem9.setSelected(true);
        jRadioButtonMenuItem9.setText("充值查询");
        jRadioButtonMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem9ActionPerformed(evt);
            }
        });
        jMenu10.add(jRadioButtonMenuItem9);

        jRadioButtonMenuItem10.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem10.setSelected(true);
        jRadioButtonMenuItem10.setText("提款查询");
        jRadioButtonMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem10ActionPerformed(evt);
            }
        });
        jMenu10.add(jRadioButtonMenuItem10);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("运营商汇总信息查询");
        jMenu11.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        jRadioButtonMenuItem11.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jRadioButtonMenuItem11.setSelected(true);
        jRadioButtonMenuItem11.setText("汇总信息查询");
        jRadioButtonMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem11ActionPerformed(evt);
            }
        });
        jMenu11.add(jRadioButtonMenuItem11);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("运营商游戏期信息查询");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu11.add(jCheckBoxMenuItem3);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Query(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query
        new GamblerQuery().setVisible(true);
    }//GEN-LAST:event_Query

    private void Bindcard(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bindcard
        new GamblerInBindCard().setVisible(true);
    }//GEN-LAST:event_Bindcard

    private void Modify(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modify
        new GamblerModify().setVisible(true);
    }//GEN-LAST:event_Modify

    private void queryaccount(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryaccount
        new GamblerAccountQuery().setVisible(true);
    }//GEN-LAST:event_queryaccount

    private void serverUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverUrlActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_serverUrlActionPerformed
    public PrivateKey getPrivateKey(String keyStorePath,
            String keyStorePassword, String alias, String aliasPassword) {
        try {
            KeyStore ks = getKeyStore(keyStorePath, keyStorePassword);
            PrivateKey key = (PrivateKey) ks.getKey(alias,
                    aliasPassword.toCharArray());
            return key;
        } catch (Exception e) {
            logger.error("", e);
        }
        return null;
    }

    private KeyStore getKeyStore(String keyStorePath, String password)
            throws Exception {
        FileInputStream is = new FileInputStream(keyStorePath);
        KeyStore ks = KeyStore.getInstance(KEY_STORE);
        ks.load(is, password.toCharArray());
        is.close();
        return ks;
    }


    private void saveserverUrl(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveserverUrl
        String server = serverUrl.getText();
        System.out.println("private key path is:" + "e:\\gamb\\gdclient.p12");
        File dir = new File("");
        String path = dir.getAbsolutePath();
        StaticVariable.privateKey = this.getPrivateKey("e:\\gamb\\gdclient.p12", "gdtest@2015", "cosmos", "gdtest@2015");
        //StaticVariable.privateKey = this.getPrivateKey(path + "\\gamb\\gdclient.p12", "gdtest@2015", "cosmos", "gdtest@2015");
        AppHeader head = new AppHeader();
        head.setType(Integer.parseInt(sendtype.getText()));//head.setType(1);//发送方类型
        head.setAction(ActionID.GAMBLER_LOGIN);//协议编号
        head.setVersion(0);//version版本号(填0)
        head.setDealer_id(dealer_id.getText().trim());//head.setDealer_id("111");//运营商ID
        head.setTerminal_id(Integer.parseInt(terminal_id.getText().trim()));//head.setTerminal_id("111");//终端机号
        head.setMobile(Mobile.getText().trim());//手机号(填0)head.setMobile("15101105612");
        head.setPhone(Phone.getText().trim());//电话号码(填0)   head.setPhone("15101105612");
        head.setSent_time(new Date().toString());//发送时间head.setSent_time("2015-07-29 12:12:12");
        //head.setSign(new byte[0]);//head.setSign("1231321".getBytes());//报文体签名
        if (head == null) {
            return;
        }
        StaticVariable.head = head;
        //information.setText("saved");
        try {
            StaticVariable.SERVERURL = server;
            RhClientProperties.setpro("serverurl", server);
            //RhClientProperties.setpro("serverport", protr);
            if (StaticVariable.httpclient != null) {
                StaticVariable.httpclient.getConnectionManager().shutdown();
            }

            // HttpUtil.KEY_STORE_CLIENT_PATH = crt1;
            // HttpUtil.KEY_STORE_PASSWORD = crt1pwd;
            // RhClientProperties.setpro("crt1", crt1);
            // RhClientProperties.setpro("crt1pwd", crt1pwd);
            //HttpUtil.initPoolConn(StaticVariable.SERVERURL, Integer.parseInt(protr.trim()));
//            HttpUtil.KEY_STORE_TRUST_PATH = crt2;
//            HttpUtil.KEY_STORE_TRUST_PASSWORD = crt2pwd;
        } catch (Exception e) {
            //information.setText(e.toString());
            //  logger.error("", e);
        }
        serverUrl.setEditable(false);
        //serverUrl1.setEditable(false);
//        serverUrl2.setEditable(true);
        //serverUrl3.setEditable(false);
//        serverUrl4.setEditable(true);
        // information.setText("server url saved");
    }//GEN-LAST:event_saveserverUrl

    private void sysTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sysTime
        new SysTimeGet().setVisible(true);
    }//GEN-LAST:event_sysTime

    private void UserRegister(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRegister
        new UserRegister().setVisible(true);
    }//GEN-LAST:event_UserRegister

    private void login(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login
        new UserLogin().setVisible(true);
    }//GEN-LAST:event_login

    private void Register(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register
        new GamblerRegister().setVisible(true);
    }//GEN-LAST:event_Register

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
        new GameRuleInfoDown().setVisible(true);
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void jRB_OpenPrizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_OpenPrizeActionPerformed
        new OpenPrizeQuery().setVisible(true);
    }//GEN-LAST:event_jRB_OpenPrizeActionPerformed

    private void jRB_DrawInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_DrawInfoActionPerformed
        new GameDrawInfo().setVisible(true);
    }//GEN-LAST:event_jRB_DrawInfoActionPerformed

    private void sendbetmore(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbetmore
        new SendBetNumberXml().setVisible(true);
    }//GEN-LAST:event_sendbetmore

    private void sendbetnumber(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbetnumber
        new SendBetNumberXml().setVisible(true);
    }//GEN-LAST:event_sendbetnumber

    private void creatBetNumber(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatBetNumber
        new CreateBetNumberDataIntoFile();
    }//GEN-LAST:event_creatBetNumber

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new DealerRechargeAgent().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jRadioButtonMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem9ActionPerformed
        new DealerRechargeAgentQuery().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new DealerAbstractAgent().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jRadioButtonMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem10ActionPerformed
        new DealerAbstractAgentQuery().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem10ActionPerformed

    private void jRadioButtonMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem11ActionPerformed
        new gamblerAccountInfoo().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem11ActionPerformed

    private void sendtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendtypeActionPerformed

    private void jRadioButtonMenuItem12creatBetNumber(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem12creatBetNumber
        new BetQuery().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem12creatBetNumber

    private void jRadioButtonMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem13ActionPerformed
        new FileNameQuery().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem13ActionPerformed

    private void jRadioButtonMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem14ActionPerformed
        new FileDownload().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem14ActionPerformed

    private void jRadioButtonMenuItem15Register(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem15Register
        new sentBet().setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem15Register

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        new TicketUndo().setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        // TODO add your handling code here:
        new DealerGameDrawQuery().setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Mobile;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField dealer_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JRadioButtonMenuItem jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButtonMenuItem jRB_DrawInfo;
    private javax.swing.JRadioButtonMenuItem jRB_OpenPrize;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem10;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem11;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem12;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem13;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem14;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem15;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem9;
    private javax.swing.JRadioButtonMenuItem login;
    private javax.swing.JTextField sendtype;
    private javax.swing.JTextField serverUrl;
    private javax.swing.JTextField terminal_id;
    // End of variables declaration//GEN-END:variables
}
