/*
 * Czech translation
 * @author Roman Matěna <info@romanmatena.cz>
 * @author Michal Marek <mich.marek@gmail.com>
 * @author Jakub Olexa <olexa@xland.cz>
 * @version 2011-03-11
 */
(function($) {
if (elFinder && elFinder.prototype.options && elFinder.prototype.options.i18n) 
	elFinder.prototype.options.i18n.cn = {
		/* errors */
		'Root directory does not exists'       : '根目录不存在',
		'Unable to connect to backend'         : '无法连接到后端',
		'Access denied'                        : '拒绝访问',
		'Invalid backend configuration'        : '无效后端配置',
		'Unknown command'                      : '未知的命令',
		'Command not allowed'                  : '命令不允许',
		'Invalid parameters'                   : '无效的参数',
		'File not found'                       : '文件未找到',
		'Invalid name'                         : '无效的名称',
		'File or folder with the same name already exists' : '具有相同名称的文件或文件夹已经存在',
		'File or folder with the same name already exists Whether covered':'具有相同名称的文件或文件夹已经存在,是否覆盖上传',
		'Unable to rename file'                : '无法重命名文件',
		'Unable to create folder'              : '无法创建文件夹',
		'Unable to create file'                : '无法创建文件',
		'No file to upload'                    : '没有文件上传',
		'Select at least one file to upload'   : '至少选择一个文件上传',
		'File exceeds the maximum allowed filesize' : '文件超过最大允许文件大小',
		'Data exceeds the maximum allowed size' : '数据超过了最大允许的大小',
		'Not allowed file type'                 : '不允许的文件类型',
		'Unable to upload file'                 : '无法上传文件',
		'Unable to upload files'                : '无法上传文件',
		'Unable to remove file'                 : '无法删除文件',
		'Unable to save uploaded file'          : '无法保存上传文件',
		'Some files was not uploaded'           : '一些文件没有上传',
		'Unable to copy into itself'            : '无法复制到本身',
		'Unable to move files'                  : '无法移动文件',
		'Unable to copy files'                  : '无法复制文件',
		'Unable to create file copy'            : '无法创建文件副本',
		'File is not an image'                  : '文件不是一个图像',
		'Unable to resize image'                : '无法调整图像',
		'Unable to write to file'               : '无法写入文件',
		'Unable to create archive'              : '无法创建存档',
		'Unable to extract files from archive'  : '无法从档案中提取文件',
		'Unable to open broken link'            : '无法打开链接',
		'File URL disabled by connector config' : '连接配置的文件路径无效',
		/* statusbar */
		'items'          : '项目',
		'selected items' : '所选项目',
		/* commands/buttons */
		'Back'                    : '后退',
		'Reload'                  : '刷新',
		'Open'                    : '打开',
		'Preview with Quick Look' : '快速预览',
		'Select file'             : '选择文件',
		'New folder'              : '新建文件夹',
		'New text file'           : '新建文本文件',
		'Upload files'            : '上传文件',
		'Download'                : '下载文件',
		'Copy'                    : '复制',
		'Cut'                     : '剪切',
		'Paste'                   : '粘贴',
		'Duplicate'               : '副本',
		'Remove'                  : '删除',
		'Rename'                  : '重命名',
		'Edit text file'          : '编辑文本文件',
		'View as icons'           : '图标视图',
		'View as list'            : '列表视图',
		'Resize image'            : '重设图像大小',
		'Create archive'          : '创建档案',
		'Uncompress archive'      : '解压缩档案',
		'Get info'                : '查看信息',
		'Help'                    : '帮助',
		'Dock/undock filemanger window' : '停靠/浮动 文件管理窗口',
		/* upload/get info dialogs */
		'Maximum allowed files size' : '允许的最大文件大小',
		'Add field'   : '添加上传文件',
		'File info'   : '文件信息',
		'Folder info' : '文件夹信息',
		'Name'        : '名称',
		'Kind'        : '类别',
		'Size'        : '大小',
		'Modified'    : '修改时间',
		'Permissions' : '权限',
		'Link to'     : '链接',
		'Dimensions'  : '规格',
		'Confirmation required' : '确认信息',
		'Are you sure you want to remove files?<br /> This cannot be undone!' : '你确定你要删除文件吗? 这将无法恢复!',
		/* permissions */
		'read'        : '读',
		'write'       : '写',
		'remove'      : '删除',
		/* dates */
		'Jan'         : '一月',
		'Feb'         : '二月',
		'Mar'         : '三月',
		'Apr'         : '四月',
		'May'         : '五月',
		'Jun'         : '六月',
		'Jul'         : '七月',
		'Aug'         : '八月',
		'Sep'         : '九月',
		'Oct'         : '十月',
		'Nov'         : '十一月',
		'Dec'         : '十二月',
		'Today'       : '今天',
		'Yesterday'   : '昨天',
		/* mimetypes */
		'Unknown'                           : '未知',
		'Folder'                            : '文件夹',
		'File'                              : '普通文件',
		'Link'                              : '链接文件',
		'Alias'                             : '别名',
		'Broken alias'                      : '破碎的别名',
		'Plain text'                        : '纯文本',
		'Postscript document'               : 'PostScript文件',
		'Application'                       : '应用',
		'Microsoft Office document'         : 'Microsoft Office文件',
		'Microsoft Word document'           : 'Microsoft Word文件',
		'Microsoft Excel document'          : 'Microsoft Excel文件',
		'Microsoft Powerpoint presentation' : 'Microsoft PPt文件',
		'Open Office document'              : 'Open Office文件',
		'Flash application'                 : 'Flash应用',
		'XML document'                      : 'XML文件',
		'Bittorrent file'                   : 'Bittorrent文件',
		'7z archive'                        : '7z压缩包',
		'TAR archive'                       : 'TAR压缩包',
		'GZIP archive'                      : 'GZIP压缩包',
		'BZIP archive'                      : 'BZIP压缩包',
		'ZIP archive'                       : 'ZIP压缩包',
		'RAR archive'                       : 'RAR压缩包',
		'Javascript application'            : 'Javascript应用',
		'PHP source'                        : 'PHP源文件',
		'HTML document'                     : 'HTML文件',
		'Javascript source'                 : 'Javascript源文件',
		'CSS style sheet'                   : 'CSS文件',
		'C source'                          : 'C源文件',
		'C++ source'                        : 'C++源文件',
		'Unix shell script'                 : 'Unix shell脚本',
		'Python source'                     : 'Python源文件',
		'Java source'                       : 'Java源文件',
		'Ruby source'                       : 'Ruby源文件',
		'Perl script'                       : 'Perl脚本',
		'BMP image'                         : 'BMP图像',
		'JPEG image'                        : 'JPEG图像',
		'GIF Image'                         : 'GIF图像',
		'PNG Image'                         : 'PNG图像',
		'TIFF image'                        : 'TIFF图像',
		'TGA image'                         : 'TGA图像',
		'Adobe Photoshop image'             : 'Adobe Photoshop图像',
		'MPEG audio'                        : 'MPEG音频文件',
		'MIDI audio'                        : 'MIDI音频文件',
		'Ogg Vorbis audio'                  : 'Ogg音频文件',
		'MP4 audio'                         : 'MP4音频文件',
		'WAV audio'                         : 'WAV音频文件',
		'DV video'                          : 'DV视频文件',
		'MP4 video'                         : 'MP4视频文件',
		'MPEG video'                        : 'MPEG视频文件',
		'AVI video'                         : 'AVI视频文件',
		'Quicktime video'                   : 'Quicktime视频文件',
		'WM video'                          : 'WM视频文件',
		'Flash video'                       : 'Flash视频文件',
		'Matroska video'                    : 'Matroska视频文件',
		'Portable Document Format (PDF)'    : 'PDF',
		// 'Shortcuts' : 'Zkratky',
		'Select all files' : '选中所有文件',
		'Copy/Cut/Paste files' : '复制/剪切/粘贴 文件',
		'Open selected file/folder' : '打开选中的文件或文件夹',
		'Open/close QuickLook window' : '打开/关闭 预览窗口',
		'Remove selected files' : '删除选中文件',
		'Selected files or current directory info' : '显示选中文件或当前目录的信息',
		'Create new directory' : '新建文件夹',
		'Open upload files form' : '打开上传文件表单',
		'Select previous file' : '选中上一个文件',
		'Select next file' : '选中下一个文件',
		'Return into previous folder' : '返回上级目录',
		'Increase/decrease files selection' : '增加/减少 选中的文件',
		'Authors'                       : '作者',
		'Sponsors'  : '赞助商',
		'elFinder: Web file manager'    : 'LoongDisk: web文件管理系统',
		'Version'                       : '版本',
		'Copyright: Studio 42 LTD'      : '',
		'Donate to support project development' : '',
		'Javascripts/PHP programming: Dmitry (dio) Levashov, dio@std42.ru' : '',
		'Python programming, techsupport: Troex Nevelin, troex@fury.scancode.ru' : '',
		'Design: Valentin Razumnih'     : '',
		'Spanish localization'          : '',
		'Icons' : '',
		'License: BSD License'          : '',
		'elFinder documentation'        : '',
		'Simple and usefull Content Management System' : '简单、有用的内容管理系统',
		'Support project development and we will place here info about you' : '',
		'Contacts us if you need help integrating elFinder in you products' : '',
		'elFinder support following shortcuts' : 'LoongDisk支持以下快捷键',
		'helpText' : '',
		'Mon' : '星期一',
		'SignatureMismatch':'你已经退出或者已经在其他地方登录',
		'userSessionNotFinded':'用户session失效，请重新登录',
		'AccessDenied':'用户没有该操作的权限',
		'Directory not empty, Are you sure you want to remove this ?':'目录不为空，您确定要继续删除文件吗? 这将无法恢复!',
		'NotEmpty':'目录不为空',
		'untitled file':'新建 文本文档',
		'AlreadyExists':'已存在相同文件',
		'NotExist':'路径不存在，请重新登陆'
	};
})(jQuery);
