/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.bestinfo.gambler.swing;

import com.alibaba.fastjson.JSONObject;
import com.bestinfo.gambler.all.HttpUtil;
import com.bestinfo.gambler.rsasign.Rsa;
import static com.bestinfo.tf.read.AdminUser.FM_PIN_CHANGEOPER;
import static com.bestinfo.tf.read.AdminUser.FM_PIN_OPER;
import static com.bestinfo.tf.read.JniTestMain.FM_OPEN_MULTIPROCESS;
import static com.bestinfo.tf.read.JniTestMain.FM_OPEN_MULTITHREAD;
import com.fmkeyjni.key_api;
import java.io.StringWriter;
import java.security.PublicKey;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.bouncycastle.util.io.pem.PemObject;
import org.bouncycastle.util.io.pem.PemWriter;
import sun.misc.BASE64Encoder;

/**
 * 更新终端表（t_tmn_info）的public_key
 * 1.开启驱动
 * 2.普通用户登录
 * 3.使用N、e值还原公钥
 * 4.发送http请求
 * 5.关闭驱动
 * 
 */
public class TFPublicKey extends javax.swing.JFrame {

    /**
     * Creates new form TFPublicKey
     */
    public TFPublicKey() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("终端Id：");

        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("修改密码");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel2.setText("新密码：");

        jLabel3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel3.setText("原密码：");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(385, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        int ret;
        String pemkey = null;
        byte[] index = new byte[]{0};
        //开启驱动
        ret = key_api.FM_SIC_OpenDevice(index, 0, FM_OPEN_MULTITHREAD|FM_OPEN_MULTIPROCESS, key_api.hDev);
        if(ret != 0){
            System.out.printf("FM_SIC_OpenDevice err, ret = %02X\n", ret);
            return;
        }
        else{
            System.out.println("open device succeed");
        }
        //普通用户登录
        String pin = "12345678";
        int pinLen;
        int[] retrynum = new int[]{0};
        pinLen = pin.length();
        ret = key_api.FM_SIC_USER_Login(key_api.hDev[0], FM_PIN_OPER, pin, pinLen, retrynum);
        if (ret != 0){
            System.out.printf("FM_SIC_USER_Login err, ret = %02X\n", ret);
            return;
        }else{
            System.out.print("succeed\n");
        }
        //生成GenRSAKeypair
        byte[] Pubkey = new byte[516];
        byte[] Prikey = new byte[1412];
        byte[] Pubkey2 = new byte[516];
        byte[] Prikey2 = new byte[1412];
        byte[] tmpPubkey = new byte[516];
        byte[] tmpPrikey = new byte[1412];
        int[] keyID = new int[1];
        int keyBits=1024;
        try {
            ret = key_api.FM_SIC_GenRSAKeypair(key_api.hDev[0], keyBits, keyID, Pubkey, Prikey);
            if (ret != 0){
                System.out.printf("FM_SIC_GenRSAKeypair err, ret = %02X\n", ret);
	        return;
	    }else{
                System.err.println("FM_SIC_GenRSAKeypair success");
            }            
        } catch (Exception ex) {
            System.out.println("Exception ex:"+ex);
        }
        System.arraycopy(Pubkey, 0, Pubkey2, 0, 516);
        System.arraycopy(Prikey, 0, Prikey2, 0, 1412);    
        ret = key_api.FM_SIC_ExportRSAKeypair(key_api.hDev[0], keyID[0], tmpPubkey, tmpPrikey);
        if (ret != 0){
            System.out.printf("FM_SIC_ExportRSAKeypair err, ret = %02X\n", ret);
            return;
        }		
        byte[] modules1024 = new byte[128];
        System.arraycopy(tmpPubkey, 4, modules1024, 0, 128);
        System.err.println("nnnnnnnnnnnnnnnnn:"+modules1024+"len:"+modules1024.length);
        String str16 = ConversionUtil.bytesToHexString(modules1024);
        System.err.println("str16："+str16);
        Rsa myrsa = new Rsa();
        String subPemKey = "";
        try {
            PublicKey pubkey = myrsa.getPublicKey(modules1024);
            byte[] keyBytes = pubkey.getEncoded();
            String gyzfc = (new BASE64Encoder()).encode(keyBytes);
            StringWriter writer = new StringWriter();
            PemWriter pemwriter = new PemWriter(writer);
            pemwriter.writeObject(new PemObject("PUBLIC KEY", keyBytes));
            pemwriter.flush();
            pemwriter.close();
            pemkey = writer.toString();
            System.out.println("pemkey:"+pemkey);
            if(pemkey == null || pemkey.length()<28){
                JOptionPane.showMessageDialog(this, "public key length is error");
                return;
            }
            subPemKey = pemkey.substring(28,pemkey.length()-28);
            System.err.println("pk str:"+subPemKey);
        } catch (Exception ex) {
            Logger.getLogger(TFPublicKey.class.getName()).log(Level.SEVERE, null, ex);
        }
        String terminalId = jTextField1.getText();
        JSONObject json = new JSONObject();
        json.put("TRMINAL_ID", terminalId);
        json.put("PEMKEY", subPemKey);

        String url="http://192.168.26.221:8751/manager/update/publickey";
        String responsexml = HttpUtil.httpSend(json.toJSONString(), url, false);
        System.err.println("responsexml："+responsexml);
        if("1".equals(responsexml)){
            JOptionPane.showMessageDialog(this, "update tmn public key success");
        }else{
            JOptionPane.showMessageDialog(this, "update tmn public key failed");
        }
        //关闭驱动
        ret = key_api.FM_SIC_CloseDevice(key_api.hDev[0]);
        System.err.println("ret @2:"+ret);
        if(ret != 0){
                System.out.printf("FM_SIC_CloseDevice err, ret = %02X\n", ret);
                return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String oldpass = jTextField3.getText();
        String newpass = jTextField2.getText();
        System.err.println("oldpass:"+oldpass+"newpass:"+newpass);
        int ret;
        int[] retrynum = new int[]{0};
        byte[] oldOperPin= oldpass.getBytes(); //new byte[]{0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x00};
        byte[] newOperPin= newpass.getBytes(); //new byte[]{0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x00};
        System.err.println("ooo:"+oldOperPin+"nnn:"+newOperPin);
        int oldPinLen = oldpass.length();//8;
        int newPinLen = newpass.length();//8;
        ret = key_api.FM_SIC_USER_ChangePin(key_api.hDev[0], FM_PIN_CHANGEOPER, oldOperPin, oldPinLen, newOperPin, newPinLen, retrynum);
        System.err.println("ret:"+ret);
        if (ret != 0){
            System.out.printf("FM_SIC_USER_ChangePin err, ret = %02X\n, retrynum = %d", ret, retrynum);
            return;
        }
        else{
            System.out.print("change pass succeed\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TFPublicKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TFPublicKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TFPublicKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TFPublicKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TFPublicKey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
